"""empty message

Revision ID: 21a8ddfeb996
Revises: 
Create Date: 2021-03-04 14:51:46.829857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21a8ddfeb996'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('found', sa.Column('test_field', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('found', 'test_field')
    # ### end Alembic commands ###
